inherit: baseqa.quesanal.lat.train

classifier: 'inherit: bioqa.quesanal.lat.classifier-libsvm'
feature-constructor: 'inherit: baseqa.quesanal.lat.feature-constructor'
qa-types-file: /bioqa/quesanal/lat/feat-label/3b-dev-qa-types-modified.yaml
