# execute
#      mvn exec:exec -Dconfig=bioasq.pre-factlist-lat-label
# to test the pipeline

configuration:
  name: pre-factlist-lat-label
  author: ziy

persistence-provider:
  inherit: baseqa.persistence.local-sqlite-persistence-provider

collection-reader:
  inherit: baseqa.collection.json.json-collection-reader
  dataset: BIOASQ-QA
  file:
    - /input/dryrun-b.json
    - /input/1b-1-b.json
    - /input/1b-2-b.json
    - /input/1b-3-b.json
    - /input/2b-1-b.json
    - /input/2b-2-b.json
    - /input/2b-3-b.json
    - /input/2b-4-b.json
    - /input/2b-5-b.json
  type: [factoid, list]
  decorators: |
    - inherit: bioasq.gs.bioasq-qa-gs-decorator
  persistence-provider: |
    inherit: baseqa.persistence.local-sqlite-persistence-provider

pipeline:
  - inherit: ecd.phase
    name: quesanal-parse
    options: |
      - inherit: bioqa.quesanal.parse-clearnlp-bioinformatics

  - inherit: ecd.phase
    name: answer-type-label-extract
    options: |
      - inherit: bioqa.quesanal.lat.answer-type-label-extract
