# execute
#      mvn exec:exec -Dconfig=bioasq.test-rocheqa
# to test the pipeline

configuration:
  name: test-rocheqa
  author: ziy

persistence-provider:
  inherit: baseqa.persistence.local-sqlite-persistence-provider

collection-reader:
  inherit: baseqa.collection.json.json-collection-reader
  dataset: BIOASQ-QA
  file:
    - /input/dryrun-a.json
#    - /input/1b-1-a.json
#    - /input/1b-2-a.json
#    - /input/1b-3-a.json
#    - /input/2b-1-a.json
#    - /input/2b-2-a.json
#    - /input/2b-3-a.json
#    - /input/2b-4-a.json
#    - /input/2b-5-a.json
#    - /input/3b-1-a.json
#    - /input/3b-2-a.json
#    - /input/3b-3-a.json
#    - /input/3b-4-a.json
#    - /input/3b-5-a.json
  type: [factoid, list, yesno, summary]
  decorators: |
    - inherit: bioasq.gs.bioasq-qa-gs-decorator
  persistence-provider: |
    inherit: baseqa.persistence.local-sqlite-persistence-provider

pipeline:
  # question analysis (Phase B)
  - inherit: ecd.phase
    name: quesanal-parse
    options: |
      - inherit: bioqa.quesanal.parse-clearnlp-bioinformatics

  - inherit: ecd.phase
    name: quesanal-concept
    options: |
      - inherit: bioqa.quesanal.concept-metamap-cached

  - inherit: ecd.phase
    name: quesanal-concept
    options: |
      - inherit: bioqa.quesanal.concept-lingpipe-genia

  - inherit: ecd.phase
    name: quesanal-concept
    options: |
      - inherit: baseqa.quesanal.concept-opennlp-np

  - inherit: ecd.phase
    name: quesanal-concept
    options: |
      - inherit: baseqa.quesanal.concept-opennlp-npppnp

  - inherit: ecd.phase
    name: quesanal-focus
    options: |
      - inherit: baseqa.quesanal.focus

  - inherit: ecd.phase
    name: quesanal-lat
    options: |
      - inherit: bioqa.quesanal.lat.predict-liblinear

  # passage retrieval (Phase A)
  - inherit: ecd.phase
    name: aquery
    options: |
      - inherit: baseqa.aquery.token-selection-pos-stoplist

  - inherit: ecd.phase
    name: retrieval-document
    options: |
      - inherit: bioqa.retrieval.document.lucene-medline

  - inherit: ecd.phase
    name: document-to-passage
    options: |
      - inherit: bioasq.retrieval.util.document-to-passage

  - inherit: ecd.phase
    name: retrieval-lucene-sentence
    options: |
      - inherit: bioqa.retrieval.passage.lucene-sentence-medline

  # information extraction (Phase B)
  - inherit: ecd.phase
    name: passage-to-view
    options: |
      - inherit: baseqa.retrieval.passage-to-view

  - inherit: ecd.phase
    name: retrieval-passage-parse
    options: |
      - inherit: bioqa.retrieval.passage-parse-clearnlp-bioinformatics

  - inherit: ecd.phase
    name: retrieval-passage-concept-metamap
    options: |
      - inherit: bioqa.retrieval.passage-concept-metamap-cached

  - inherit: ecd.phase
    name: retrieval-passage-concept-lingpipe
    options: |
      - inherit: bioqa.retrieval.passage-concept-lingpipe-genia

  - inherit: ecd.phase
    name: quesanal-concept
    options: |
      - inherit: baseqa.retrieval.passage-concept-opennlp-np

  - inherit: ecd.phase
    name: quesanal-concept
    options: |
      - inherit: baseqa.retrieval.passage-concept-opennlp-npppnp

  - inherit: ecd.phase
    name: concept-search-uts
    options: |
      - inherit: bioqa.retrieval.concept-search-uts-cached

  - inherit: ecd.phase
    name: concept-merge
    options: |
      - inherit: baseqa.retrieval.concept-merge

  # answer generation and ranking (Phase B)
  - inherit: ecd.phase
    name: answer-generator
    options: |
      - inherit: bioqa.answer.generate
#      - inherit: bioqa.answer.cao-predict-crf

  - inherit: ecd.phase
    name: answer-modifier
    options: |
      - inherit: baseqa.answer.modify

  - inherit: ecd.phase
    name: answer-independent-rank
    options: |
      - inherit: bioqa.answer.score-predict-liblinear
#      - inherit: baseqa.answer.score-simple

  - inherit: ecd.phase
    name: answer-collective-rank
    options: |
      - inherit: bioqa.answer.collective-score-predict-liblinear

  - inherit: ecd.phase
    name: answer-pruner
    options: |
      - inherit: baseqa.answer.pruner

post-process:
#  - inherit: baseqa.cas-serialize

  # concept evaluation
  - inherit: baseqa.eval.base
    calculator: |
      inherit: baseqa.eval.calculator.retrieval-eval-calculator
    evaluatee-provider: |
      inherit: baseqa.eval.evaluatee.concept-evaluatee-provider
    persistence-provider: |
      inherit: baseqa.eval.persistence.jdbc-eval-persistence-provider

  # triple evaluation
  - inherit: baseqa.eval.base
    calculator: |
      inherit: baseqa.eval.calculator.retrieval-eval-calculator
    evaluatee-provider: |
      inherit: baseqa.eval.evaluatee.triple-evaluatee-provider
    persistence-provider: |
      inherit: baseqa.eval.persistence.jdbc-eval-persistence-provider

  # document evaluation
  - inherit: baseqa.eval.base
    calculator: |
      inherit: baseqa.eval.calculator.retrieval-eval-calculator
    evaluatee-provider: |
      inherit: baseqa.eval.evaluatee.document-evaluatee-provider
    persistence-provider: |
      inherit: baseqa.eval.persistence.jdbc-eval-persistence-provider

  # trec passage evaluation
  - inherit: baseqa.eval.base
    calculator: |
      inherit: baseqa.eval.calculator.trec-passage-map-eval-calculator
    evaluatee-provider: |
      inherit: baseqa.eval.evaluatee.passage-evaluatee-provider
    persistence-provider: |
      inherit: baseqa.eval.persistence.jdbc-eval-persistence-provider

  # passage evaluation
  - inherit: baseqa.eval.base
    calculator: |
      inherit: baseqa.eval.calculator.passage-map-eval-calculator
    evaluatee-provider: |
      inherit: baseqa.eval.evaluatee.passage-evaluatee-provider
    persistence-provider: |
      inherit: baseqa.eval.persistence.jdbc-eval-persistence-provider

  # answer evaluation
  - inherit: baseqa.eval.base
    calculator: |
      inherit: bioasq.eval.calculator.answer-eval-calculator
    evaluatee-provider: |
      inherit: baseqa.eval.evaluatee.answer-evaluatee-provider
    persistence-provider: |
      inherit: baseqa.eval.persistence.jdbc-eval-persistence-provider

  # report
  - inherit: report.csv-report-generator
    builders: |
      - inherit: baseqa.report.accumulated-measurements-report-component

  # submission
  - inherit: bioasq.collection.json.json-cas-consumer
